import { EOL } from 'node:os';

// autogenerated solution file, for help see https://github.com/beakerandjake/advent-of-code-runner

/**
 * Returns the solution for part one of this puzzle.
 * @param {String} input - The input for this days puzzle.
 * @returns {Number|String}
 */
export const partOne = (input = '') => {
  const elves = input
    .split('\n\n')
    .map((elf) => elf.split('\n').reduce((acc, calorie) => acc + parseInt(calorie, 10), 0))
    .sort((a, b) => a - b)
    .reverse();

  return elves[0];
};

/**
 * Returns the solution for part two of this puzzle.
 * @param {String} input - The input for this days puzzle.
 * @returns {Number|String}
 */
export const partTwo = (input = '') => {
  const [first, second, third] = input
    .split('\n\n')
    .map((elf) => elf.split('\n').reduce((acc, calorie) => acc + parseInt(calorie, 10), 0))
    .sort((a, b) => a - b)
    .reverse();

  return first + second + third;
};
